import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

export default function Home({ data }) {
  console.log(data.results);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="grid grid-cols-4 text-center font-kanit my-5">
        {data.results.map(show => (
          <div
            key={show.id}
            className=" flex
            flex-col
            justify-center
            items-center
            text-center
            my-3"
          >
            <Image
              src={`https://image.tmdb.org/t/p/w500/${show.poster_path}`}
              alt="fun"
              height={200}
              width={200}
              className="rounded"
            />
            <h2 className="text-3xl text-center font-kanit pt-2">
              {show.name}
            </h2>
            <h3 className="text-xs text-center">{show.first_air_date}</h3>
          </div>
        ))}
      </div>
      <Footer />
    </div>
  );
}

export const getServerSideProps = async () => {
  // Fetch data from external API
  const res = await fetch(
    `https://api.themoviedb.org/3/tv/top_rated?api_key=${process.env.TMDB_API_KEY}&language=en-US&page=1`
  );
  const data = await res.json();

  // Pass data to the page via props
  return { props: { data } };
};
